name             'rails_app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures rails_app'
long_description 'Installs/Configures rails_app'
version          '0.1.0'

depends 'nginx', '~> 2.0'
depends 'mysql', '5.3.6'
